# Generated by Django 4.1.3 on 2022-12-09 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.DateField(null=True)),
                ('developer', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover', models.CharField(max_length=200, null=True)),
                ('slug', models.CharField(max_length=200)),
                ('rating', models.PositiveSmallIntegerField(null=True)),
                ('rating_count', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'игра',
                'verbose_name_plural': 'игры',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'жанры',
            },
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
            ],
            options={
                'verbose_name': 'платформа',
                'verbose_name_plural': 'платформы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('nickname', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='ReviewSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'источник',
                'verbose_name_plural': 'источники',
            },
        ),
        migrations.CreateModel(
            name='Websites',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
            ],
            options={
                'verbose_name': 'сайт',
                'verbose_name_plural': 'сайты',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='ReleaseDates',
            fields=[
                ('platform', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
            ],
            options={
                'verbose_name': 'Дата выхода',
                'verbose_name_plural': 'Даты выхода',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rate', models.PositiveSmallIntegerField(null=True)),
                ('game', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.game')),
                ('review', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_app.reviews')),
            ],
            options={
                'verbose_name': 'библиотека',
                'verbose_name_plural': 'библиотеки',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('image_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game')),
            ],
            options={
                'verbose_name': 'Картинки',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game_app.genres'),
        ),
        migrations.AddField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(to='game_app.platforms'),
        ),
    ]
