# Generated by Django 4.1.3 on 2022-12-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasedates',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='websites',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='releasedates',
            name='platform',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='websites',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
