# Generated by Django 4.1.3 on 2022-12-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_releasedates_id_websites_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='game_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='releasedates',
            name='game_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='game_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='websites',
            name='game_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
