# Generated by Django 4.1.3 on 2022-12-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_alter_images_game_id_alter_releasedates_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websites',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
