# Generated by Django 4.1.3 on 2022-12-11 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_images_game_id_alter_releasedates_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='added_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
