# Generated by Django 4.1.3 on 2022-12-25 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0010_library_id_alter_library_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game'),
        ),
        migrations.AlterField(
            model_name='library',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_app.reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_app.game'),
        ),
    ]
