# Generated by Django 4.1.3 on 2023-02-08 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0012_alter_library_rate_alter_library_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('IsAnswered', models.BooleanField(blank=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Техническая поддержка',
                'verbose_name_plural': 'Технические поддержки',
            },
        ),
    ]
