# Generated by Django 4.1.3 on 2023-02-20 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0013_techsupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Тема рассылки',
                'verbose_name_plural': 'Темы для рассылок',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('send_at', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(default='Topic was deleted', on_delete=django.db.models.deletion.SET_DEFAULT, to='game_app.messagetopics')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тема рассылки',
                'verbose_name_plural': 'Темы для рассылок',
            },
        ),
    ]
