# Generated by Django 4.1.3 on 2023-02-20 08:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0016_remove_message_users_messagetopics_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shown_to',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
