# Generated by Django 4.1.3 on 2023-02-28 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0018_alter_message_shown_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='shown_to',
            field=models.ManyToManyField(blank=True, editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
