# Generated by Django 4.1.3 on 2023-02-28 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game_app', '0019_alter_message_shown_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL)),
                ('dislike', models.ManyToManyField(related_name='comment_dislike', to=settings.AUTH_USER_MODEL)),
                ('like', models.ManyToManyField(related_name='comment_like', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщения чата',
            },
        ),
    ]
