# Generated by Django 4.1.3 on 2023-03-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0020_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'Сообщениe чата', 'verbose_name_plural': 'Сообщения чата'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='game_app.chatmessage'),
        ),
    ]
